[template]
description = "ICP project with local Bitcoin integration"

[placeholders]
backend_type = { type = "string", prompt = "Choose your backend language:", choices = ["rust", "motoko"], default = "rust" }
network_type = { type = "string", prompt = "Use the default network or a dockerized one?", choices = ["Default", "Docker"], default = "Default" }

[conditional.'backend_type == "rust"']
ignore = [ "motoko-backend" ]

[conditional.'backend_type == "motoko"']
ignore = [ "rust-backend" ]

[hooks]
pre = ["rename-backend-dir.rhai"]
